name: build_and_push
on:
  push:
    paths-ignore:
      - '.github/**'
jobs:
  docker-build:
    runs-on: ubuntu-latest
    permissions:
      conetents: write
    steps:
      - name: Log in to Docker Container Registry
        uses: docker/login-action@v3
        with:
          #registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: checkout
        uses: actions/checkout@v4
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          psuh: true
          tags: ${{ secrets.DOCKER_USERNAME }}/express-practice:latest
